<?php

use App\Http\Controllers\Auth\AutenticacionUsuarioController;
use App\Http\Controllers\Auth\SolicitudCodigoCorreoController;
use App\Http\Controllers\Auth\NuevaClaveController;
use App\Http\Controllers\Auth\PerfilController;

use App\Http\Controllers\Usuario\Administrador\Personal\AdministradorUsuarioController;
use App\Http\Controllers\Usuario\Administrador\Personal\AdministradorDocenteController;
use App\Http\Controllers\Usuario\Administrador\Personal\AdministradorAuxiliarController;
use App\Http\Controllers\Usuario\Administrador\Personal\AdministradorEstudianteController;
use App\Http\Controllers\Usuario\Administrador\Personal\AdministradorAdministrativoController;
use App\Http\Controllers\Usuario\Administrador\Carrera\AdministradorAsignaturaController;
use App\Http\Controllers\Usuario\Administrador\Carrera\AdministradorAulaController;
use App\Http\Controllers\Usuario\Administrador\Carrera\AdministradorHorarioController;
use App\Http\Controllers\Usuario\Administrador\Carrera\AdministradorMencionController;
use App\Http\Controllers\Usuario\Administrador\Carrera\AdministradorPlanEstudioController;
use App\Http\Controllers\Usuario\Administrador\Inscripcion\AdministradorAperturaController;
use App\Http\Controllers\Usuario\Administrador\Inscripcion\AdministradorAuxiliaturaController;
use App\Http\Controllers\Usuario\Administrador\Inscripcion\AdministradorDocenciaController;
use App\Http\Controllers\Usuario\Administrador\AdministradorPanelControlController;

use App\Http\Controllers\Usuario\Administrativo\PublicacionController;

use App\Http\Controllers\Usuario\Docente\DocenteDocenciaController;
use App\Http\Controllers\Usuario\Docente\DocentePonderacionController;
use App\Http\Controllers\Usuario\Docente\DocenteNotaController;
use App\Http\Controllers\Usuario\Docente\DocenteInscritoController;
use App\Http\Controllers\Usuario\Docente\DocenteAnuncioController;

use App\Http\Controllers\Usuario\Auxiliar\AuxiliarAuxiliaturaController;
use App\Http\Controllers\Usuario\Auxiliar\AuxiliarPonderacionController;
use App\Http\Controllers\Usuario\Auxiliar\AuxiliarNotaController;
use App\Http\Controllers\Usuario\Auxiliar\AuxiliarInscritoController;
use App\Http\Controllers\Usuario\Auxiliar\AuxiliarAnuncioController;

use App\Http\Controllers\Usuario\Estudiante\InscripcionController;
use App\Http\Controllers\Usuario\Estudiante\NotaController;
use App\Http\Controllers\Usuario\Estudiante\HorarioController;

use App\Http\Controllers\InicioController;

use Illuminate\Support\Facades\Route;

Route::get('/iniciar-sesion', [AutenticacionUsuarioController::class, 'indice'])->name('iniciar-sesion');
Route::post('/iniciar-sesion', [AutenticacionUsuarioController::class, 'autenticar'])->name('iniciar-sesion.autenticar');
Route::post('/cerrar-sesion', [AutenticacionUsuarioController::class, 'destruir'])->name('cerrar-sesion');
Route::get('/cerrar-sesion', [AutenticacionUsuarioController::class, 'destruir'])->name('cerrar-sesion');

Route::get('/codigo-correo', [SolicitudCodigoCorreoController::class, 'indice'])->name('solicitud-codigo-correo');
Route::post('/codigo-correo', [SolicitudCodigoCorreoController::class, 'almacenar'])->name('solicitud-codigo-correo.almacenar');

Route::get('/nueva-clave', [NuevaClaveController::class, 'indice'])->name('nueva-clave');
Route::post('/nueva-clave', [NuevaClaveController::class, 'actualizar'])->name('nueva-clave.actualizar');

Route::get('/perfil', [PerfilController::class, 'indice'])->name('perfil')->middleware('auth');
Route::get('/cambiar-rol', [InicioController::class, 'indice']);
Route::post('/cambiar-rol', [PerfilController::class, 'cambiarRol'])->name('cambiar-rol');
Route::get('/perfil/subir-foto', [PerfilController::class, 'indice']);
Route::post('/perfil/subir-foto', [PerfilController::class, 'subirFotoPerfil'])->name('perfil.subir-foto');
Route::get('/perfil/actualizar-domicilio', [PerfilController::class, 'indice']);
Route::post('/perfil/actualizar-domicilio', [PerfilController::class, 'actualizarDomicilio'])->name('perfil.actualizar-domicilio');
Route::get('/perfil/actualizar-correo', [PerfilController::class, 'indice']);
Route::post('/perfil/actualizar-correo', [PerfilController::class, 'actualizarCorreo'])->name('perfil.actualizar-correo');
Route::get('/perfil/actualizar-celular', [PerfilController::class, 'indice']);
Route::post('/perfil/actualizar-celular', [PerfilController::class, 'actualizarCelular'])->name('perfil.actualizar-celular');
Route::get('/perfil/actualizar-clave', [PerfilController::class, 'indice']);
Route::post('/perfil/actualizar-clave', [PerfilController::class, 'actualizarClave'])->name('perfil.actualizar-clave');

// Route::group(['middleware' => 'administrador'], function () {
Route::middleware(['auth', 'administrador'])->group(function () {
    Route::post('/administrador/usuarios/buscar', [AdministradorUsuarioController::class, 'buscar'])->name('administrador.usuarios.buscar');
    Route::get('/administrador/usuarios/indice', [AdministradorUsuarioController::class, 'indice'])->name('administrador.usuarios');
    Route::get('/administrador/usuarios/buscar', [AdministradorUsuarioController::class, 'indice']);
    Route::post('/administrador/usuarios/actualizar', [AdministradorUsuarioController::class, 'actualizar'])->name('administrador.usuarios.actualizar');
    Route::get('/administrador/usuarios/actualizar', [AdministradorUsuarioController::class, 'indice']);
    Route::post('/administrador/usuarios/crear', [AdministradorUsuarioController::class, 'crear'])->name('administrador.usuarios.crear');
    Route::get('/administrador/usuarios/crear', [AdministradorUsuarioController::class, 'indice']);
    Route::post('/administrador/usuarios/eliminar', [AdministradorUsuarioController::class, 'eliminar'])->name('administrador.usuarios.eliminar');
    Route::get('/administrador/usuarios/eliminar', [AdministradorUsuarioController::class, 'indice']);
    Route::post('/administrador/usuarios/reiniciar-clave', [AdministradorUsuarioController::class, 'reiniciarClave'])->name('administrador.usuarios.reiniciar-clave');
    Route::get('/administrador/usuarios/reiniciar-clave', [AdministradorUsuarioController::class, 'indice']);
    Route::post('/administrador/usuarios/habilitar', [AdministradorUsuarioController::class, 'habilitar'])->name('administrador.usuarios.habilitar');
    Route::get('/administrador/usuarios/habilitar', [AdministradorUsuarioController::class, 'indice']);
    Route::post('/administrador/usuarios/inhabilitar', [AdministradorUsuarioController::class, 'inhabilitar'])->name('administrador.usuarios.inhabilitar');
    Route::get('/administrador/usuarios/inhabilitar', [AdministradorUsuarioController::class, 'indice']);
    Route::get('/administrador/administrativos/indice', [AdministradorAdministrativoController::class, 'indice'])->name('administrador.administrativos');
    Route::post('/administrador/administrativos/buscar', [AdministradorAdministrativoController::class, 'buscar'])->name('administrador.administrativos.buscar');
    Route::get('/administrador/administrativos/buscar', [AdministradorAdministrativoController::class, 'indice']);
    Route::post('/administrador/administrativos/actualizar', [AdministradorAdministrativoController::class, 'actualizar'])->name('administrador.administrativos.actualizar');
    Route::get('/administrador/administrativos/actualizar', [AdministradorAdministrativoController::class, 'indice']);
    Route::post('/administrador/administrativos/agregar', [AdministradorAdministrativoController::class, 'agregar'])->name('administrador.administrativos.agregar');
    Route::get('/administrador/administrativos/agregar', [AdministradorAdministrativoController::class, 'indice']);
    Route::post('/administrador/administrativos/eliminar', [AdministradorAdministrativoController::class, 'eliminar'])->name('administrador.administrativos.eliminar');
    Route::get('/administrador/administrativos/eliminar', [AdministradorAdministrativoController::class, 'indice']);
    Route::post('/administrador/administrativos/habilitar', [AdministradorAdministrativoController::class, 'habilitar'])->name('administrador.administrativos.habilitar');
    Route::get('/administrador/administrativos/habilitar', [AdministradorAdministrativoController::class, 'indice']);
    Route::post('/administrador/administrativos/inhabilitar', [AdministradorAdministrativoController::class, 'inhabilitar'])->name('administrador.administrativos.inhabilitar');
    Route::get('/administrador/administrativos/inhabilitar', [AdministradorAdministrativoController::class, 'indice']);
    Route::get('/administrador/auxiliares/indice', [AdministradorAuxiliarController::class, 'indice'])->name('administrador.auxiliares');
    Route::post('/administrador/auxiliares/buscar', [AdministradorAuxiliarController::class, 'buscar'])->name('administrador.auxiliares.buscar');
    Route::get('/administrador/auxiliares/buscar', [AdministradorAuxiliarController::class, 'indice']);
    Route::post('/administrador/auxiliares/actualizar', [AdministradorAuxiliarController::class, 'actualizar'])->name('administrador.auxiliares.actualizar');
    Route::get('/administrador/auxiliares/actualizar', [AdministradorAuxiliarController::class, 'indice']);
    Route::post('/administrador/auxiliares/agregar', [AdministradorAuxiliarController::class, 'agregar'])->name('administrador.auxiliares.agregar');
    Route::get('/administrador/auxiliares/agregar', [AdministradorAuxiliarController::class, 'indice']);
    Route::post('/administrador/auxiliares/eliminar', [AdministradorAuxiliarController::class, 'eliminar'])->name('administrador.auxiliares.eliminar');
    Route::get('/administrador/auxiliares/eliminar', [AdministradorAuxiliarController::class, 'indice']);
    Route::post('/administrador/auxiliares/habilitar', [AdministradorAuxiliarController::class, 'habilitar'])->name('administrador.auxiliares.habilitar');
    Route::get('/administrador/auxiliares/habilitar', [AdministradorAuxiliarController::class, 'indice']);
    Route::post('/administrador/auxiliares/inhabilitar', [AdministradorAuxiliarController::class, 'inhabilitar'])->name('administrador.auxiliares.inhabilitar');
    Route::get('/administrador/auxiliares/inhabilitar', [AdministradorAuxiliarController::class, 'indice']);
    Route::get('/administrador/docentes/indice', [AdministradorDocenteController::class, 'indice'])->name('administrador.docentes');
    Route::post('/administrador/docentes/buscar', [AdministradorDocenteController::class, 'buscar'])->name('administrador.docentes.buscar');
    Route::get('/administrador/docentes/buscar', [AdministradorDocenteController::class, 'indice']);
    Route::post('/administrador/docentes/actualizar', [AdministradorDocenteController::class, 'actualizar'])->name('administrador.docentes.actualizar');
    Route::get('/administrador/docentes/actualizar', [AdministradorDocenteController::class, 'indice']);
    Route::post('/administrador/docentes/agregar', [AdministradorDocenteController::class, 'agregar'])->name('administrador.docentes.agregar');
    Route::get('/administrador/docentes/agregar', [AdministradorDocenteController::class, 'indice']);
    Route::post('/administrador/docentes/eliminar', [AdministradorDocenteController::class, 'eliminar'])->name('administrador.docentes.eliminar');
    Route::get('/administrador/docentes/eliminar', [AdministradorDocenteController::class, 'indice']);
    Route::post('/administrador/docentes/habilitar', [AdministradorDocenteController::class, 'habilitar'])->name('administrador.docentes.habilitar');
    Route::get('/administrador/docentes/habilitar', [AdministradorDocenteController::class, 'indice']);
    Route::post('/administrador/docentes/inhabilitar', [AdministradorDocenteController::class, 'inhabilitar'])->name('administrador.docentes.inhabilitar');
    Route::get('/administrador/docentes/inhabilitar', [AdministradorDocenteController::class, 'indice']);
    Route::get('/administrador/estudiantes/indice', [AdministradorEstudianteController::class, 'indice'])->name('administrador.estudiantes');
    Route::post('/administrador/estudiantes/buscar', [AdministradorEstudianteController::class, 'buscar'])->name('administrador.estudiantes.buscar');
    Route::get('/administrador/estudiantes/buscar', [AdministradorEstudianteController::class, 'indice']);
    Route::post('/administrador/estudiantes/actualizar', [AdministradorEstudianteController::class, 'actualizar'])->name('administrador.estudiantes.actualizar');
    Route::get('/administrador/estudiantes/actualizar', [AdministradorEstudianteController::class, 'indice']);
    Route::post('/administrador/estudiantes/agregar', [AdministradorEstudianteController::class, 'agregar'])->name('administrador.estudiantes.agregar');
    Route::get('/administrador/estudiantes/agregar', [AdministradorEstudianteController::class, 'indice']);
    Route::post('/administrador/estudiantes/eliminar', [AdministradorEstudianteController::class, 'eliminar'])->name('administrador.estudiantes.eliminar');
    Route::get('/administrador/estudiantes/eliminar', [AdministradorEstudianteController::class, 'indice']);
    Route::post('/administrador/estudiantes/habilitar', [AdministradorEstudianteController::class, 'habilitar'])->name('administrador.estudiantes.habilitar');
    Route::get('/administrador/estudiantes/habilitar', [AdministradorEstudianteController::class, 'indice']);
    Route::post('/administrador/estudiantes/inhabilitar', [AdministradorEstudianteController::class, 'inhabilitar'])->name('administrador.estudiantes.inhabilitar');
    Route::get('/administrador/estudiantes/inhabilitar', [AdministradorEstudianteController::class, 'indice']);
    
    Route::get('/administrador/asignaturas/indice/{planEstudiosId?}/{mencionId?}', [AdministradorAsignaturaController::class, 'indice'])->name('administrador.asignaturas');
    Route::get('/administrador/asignaturas/buscar', [AdministradorAsignaturaController::class, 'buscar'])->name('administrador.asignaturas.buscar');
    // Route::get('/administrador/asignaturas/buscar', [AdministradorAsignaturaController::class, 'indice']);
    Route::post('/administrador/asignaturas/actualizar', [AdministradorAsignaturaController::class, 'actualizar'])->name('administrador.asignaturas.actualizar');
    Route::get('/administrador/asignaturas/actualizar', [AdministradorAsignaturaController::class, 'indice']);
    Route::post('/administrador/asignaturas/eliminar', [AdministradorAsignaturaController::class, 'eliminar'])->name('administrador.asignaturas.eliminar');
    Route::get('/administrador/asignaturas/eliminar', [AdministradorAsignaturaController::class, 'indice']);
    Route::post('/administrador/asignaturas/crear', [AdministradorAsignaturaController::class, 'crear'])->name('administrador.asignaturas.crear');
    Route::get('/administrador/asignaturas/crear', [AdministradorAsignaturaController::class, 'indice']);
    Route::post('/administrador/asignaturas/agregar', [AdministradorAsignaturaController::class, 'agregar'])->name('administrador.asignaturas.agregar');
    Route::get('/administrador/asignaturas/agregar', [AdministradorAsignaturaController::class, 'indice']);
    Route::get('/administrador/aulas/indice', [AdministradorAulaController::class, 'indice'])->name('administrador.aulas');
    Route::post('/administrador/aulas/actualizar', [AdministradorAulaController::class, 'actualizar'])->name('administrador.aulas.actualizar');
    Route::get('/administrador/aulas/actualizar', [AdministradorAulaController::class, 'indice']);
    Route::post('/administrador/aulas/eliminar', [AdministradorAulaController::class, 'eliminar'])->name('administrador.aulas.eliminar');
    Route::get('/administrador/aulas/eliminar', [AdministradorAulaController::class, 'indice']);
    Route::post('/administrador/aulas/crear', [AdministradorAulaController::class, 'crear'])->name('administrador.aulas.crear');
    Route::get('/administrador/aulas/crear', [AdministradorAulaController::class, 'indice']);
    Route::get('/administrador/horarios/indice', [AdministradorAulaController::class, 'indice'])->name('administrador.horarios');
    Route::get('/administrador/menciones/indice', [AdministradorMencionController::class, 'indice'])->name('administrador.menciones');
    Route::post('/administrador/menciones/actualizar', [AdministradorMencionController::class, 'actualizar'])->name('administrador.menciones.actualizar');
    Route::get('/administrador/menciones/actualizar', [AdministradorMencionController::class, 'indice']);
    Route::post('/administrador/menciones/eliminar', [AdministradorMencionController::class, 'eliminar'])->name('administrador.menciones.eliminar');
    Route::get('/administrador/menciones/eliminar', [AdministradorMencionController::class, 'indice']);
    Route::post('/administrador/menciones/crear', [AdministradorMencionController::class, 'crear'])->name('administrador.menciones.crear');
    Route::get('/administrador/menciones/crear', [AdministradorMencionController::class, 'indice']);
    Route::get('/administrador/planes-estudios/indice', [AdministradorPlanEstudioController::class, 'indice'])->name('administrador.planes-estudios');
    Route::post('/administrador/planes-estudios/actualizar', [AdministradorPlanEstudioController::class, 'actualizar'])->name('administrador.planes-estudios.actualizar');
    Route::get('/administrador/planes-estudios/actualizar', [AdministradorPlanEstudioController::class, 'indice']);
    Route::post('/administrador/planes-estudios/eliminar', [AdministradorPlanEstudioController::class, 'eliminar'])->name('administrador.planes-estudios.eliminar');
    Route::get('/administrador/planes-estudios/eliminar', [AdministradorPlanEstudioController::class, 'indice']);
    Route::post('/administrador/planes-estudios/crear', [AdministradorPlanEstudioController::class, 'crear'])->name('administrador.planes-estudios.crear');
    Route::get('/administrador/planes-estudios/crear', [AdministradorPlanEstudioController::class, 'indice']);

    Route::get('/administrador/aperturas/indice/{planEstudioId?}/{mencionId?}/{periodo?}/{gestion?}/', [AdministradorAperturaController::class, 'indice'])->name('administrador.aperturas');
    // Route::post('/administrador/aperturas/indice', [AdministradorAperturaController::class, 'indice'])->name('administrador.aperturas');
    Route::post('/administrador/aperturas/buscar', [AdministradorAperturaController::class, 'buscar'])->name('administrador.aperturas.buscar');
    Route::get('/administrador/aperturas/buscar', [AdministradorAperturaController::class, 'indice']);
    Route::post('/administrador/aperturas/crear-paralelo', [AdministradorAperturaController::class, 'crearParalelo'])->name('administrador.aperturas.crear-paralelo');
    Route::get('/administrador/aperturas/crear-paralelo', [AdministradorAperturaController::class, 'indice']);
    Route::post('/administrador/aperturas/actualizar-paralelo', [AdministradorAperturaController::class, 'actualizarParalelo'])->name('administrador.aperturas.actualizar-paralelo');
    Route::get('/administrador/aperturas/actualizar-paralelo', [AdministradorAperturaController::class, 'indice']);
    Route::post('/administrador/aperturas/eliminar-paralelo', [AdministradorAperturaController::class, 'eliminarParalelo'])->name('administrador.aperturas.eliminar-paralelo');
    Route::get('/administrador/aperturas/eliminar-paralelo', [AdministradorAperturaController::class, 'indice']);
    Route::post('/administrador/aperturas/habilitar', [AdministradorAperturaController::class, 'habilitar'])->name('administrador.aperturas.habilitar');
    Route::get('/administrador/aperturas/habilitar', [AdministradorAperturaController::class, 'indice']);
    Route::post('/administrador/aperturas/deshabilitar', [AdministradorAperturaController::class, 'deshabilitar'])->name('administrador.aperturas.deshabilitar');
    Route::get('/administrador/aperturas/deshabilitar', [AdministradorAperturaController::class, 'indice']);
    Route::post('/administrador/aperturas/laboratorio-independiente', [AdministradorAperturaController::class, 'LaboratorioIndependiente'])->name('administrador.aperturas.laboratorio-independiente');
    Route::get('/administrador/aperturas/laboratorio-independiente', [AdministradorAperturaController::class, 'indice']);
    Route::post('/administrador/aperturas/laboratorio-dependiente', [AdministradorAperturaController::class, 'LaboratorioDependiente'])->name('administrador.aperturas.laboratorio-dependiente');
    Route::get('/administrador/aperturas/laboratorio-dependiente', [AdministradorAperturaController::class, 'indice']);
    Route::post('/administrador/aperturas/eliminar-laboratorio', [AdministradorAperturaController::class, 'eliminarLaboratorio'])->name('administrador.aperturas.eliminar-laboratorio');
    Route::get('/administrador/aperturas/eliminar-laboratorio', [AdministradorAperturaController::class, 'indice']);
    Route::post('/administrador/aperturas/crear-laboratorio', [AdministradorAperturaController::class, 'crearLaboratorio'])->name('administrador.aperturas.crear-laboratorio');
    Route::get('/administrador/aperturas/crear-laboratorio', [AdministradorAperturaController::class, 'indice']);
    Route::get('/administrador/auxiliaturas/indice/{planEstudioId?}/{mencionId?}/{periodo?}/{gestion?}', [AdministradorAuxiliaturaController::class, 'indice'])->name('administrador.auxiliaturas');
    Route::post('/administrador/auxiliaturas/buscar', [AdministradorAuxiliaturaController::class, 'buscar'])->name('administrador.auxiliaturas.buscar');
    Route::get('/administrador/auxiliaturas/buscar', [AdministradorAuxiliaturaController::class, 'indice']);
    Route::post('/administrador/auxiliaturas/actualizar', [AdministradorAuxiliaturaController::class, 'actualizar'])->name('administrador.auxiliaturas.actualizar');
    Route::get('/administrador/auxiliaturas/actualizar', [AdministradorAuxiliaturaController::class, 'indice']);
    Route::post('/administrador/auxiliaturas/crear-grupo', [AdministradorAuxiliaturaController::class, 'crearGrupo'])->name('administrador.auxiliaturas.crear-grupo');
    Route::get('/administrador/auxiliaturas/crear-grupo', [AdministradorAuxiliaturaController::class, 'indice']);
    Route::post('/administrador/auxiliaturas/actualizar-grupo', [AdministradorAuxiliaturaController::class, 'actualizarGrupo'])->name('administrador.auxiliaturas.actualizar-grupo');
    Route::get('/administrador/auxiliaturas/actualizar-grupo', [AdministradorAuxiliaturaController::class, 'indice']);
    Route::post('/administrador/auxiliaturas/eliminar-grupo', [AdministradorAuxiliaturaController::class, 'eliminarGrupo'])->name('administrador.auxiliaturas.eliminar-grupo');
    Route::get('/administrador/auxiliaturas/eliminar-grupo', [AdministradorAuxiliaturaController::class, 'indice']);
    Route::get('/administrador/docencias/indice/{planEstudioId?}/{mencionId?}/{periodo?}/{gestion?}', [AdministradorDocenciaController::class, 'indice'])->name('administrador.docencias');
    Route::post('/administrador/docencias/buscar', [AdministradorDocenciaController::class, 'buscar'])->name('administrador.docencias.buscar');
    Route::get('/administrador/docencias/buscar', [AdministradorDocenciaController::class, 'indice']);
    Route::post('/administrador/docencias/actualizar', [AdministradorDocenciaController::class, 'actualizar'])->name('administrador.docencias.actualizar');
    Route::get('/administrador/docencias/actualizar', [AdministradorDocenciaController::class, 'indice']);
    Route::post('/administrador/docencias/crear-clase', [AdministradorDocenciaController::class, 'crearClase'])->name('administrador.docencias.crear-clase');
    Route::get('/administrador/docencias/crear-clase', [AdministradorDocenciaController::class, 'indice']);
    Route::post('/administrador/docencias/actualizar-clase', [AdministradorDocenciaController::class, 'actualizarClase'])->name('administrador.docencias.actualizar-clase');
    Route::get('/administrador/docencias/actualizar-clase', [AdministradorDocenciaController::class, 'indice']);
    Route::post('/administrador/docencias/eliminar-clase', [AdministradorDocenciaController::class, 'eliminarClase'])->name('administrador.docencias.eliminar-clase');
    Route::get('/administrador/docencias/eliminar-clase', [AdministradorDocenciaController::class, 'indice']);

    Route::get('/administrador/panel-control/indice', [AdministradorPanelControlController::class, 'indice'])->name('administrador.panel-control');
    Route::post('/administrador/panel-control/habilitar-apertura', [AdministradorPanelControlController::class, 'habilitarApertura'])->name('administrador.panel-control.habilitar-apertura');
    Route::get('/administrador/panel-control/habilitar-apertura', [AdministradorPanelControlController::class, 'indice']);
    Route::post('/administrador/panel-control/habilitar-inscripcion', [AdministradorPanelControlController::class, 'habilitarInscripcion'])->name('administrador.panel-control.habilitar-inscripcion');
    Route::get('/administrador/panel-control/habilitar-inscripcion', [AdministradorPanelControlController::class, 'indice']);
    Route::post('/administrador/panel-control/deshabilitar-inscripcion', [AdministradorPanelControlController::class, 'deshabilitarInscripcion'])->name('administrador.panel-control.deshabilitar-inscripcion');
    Route::get('/administrador/panel-control/deshabilitar-inscripcion', [AdministradorPanelControlController::class, 'indice']);
    Route::post('/administrador/panel-control/habilitar-periodo', [AdministradorPanelControlController::class, 'habilitarPeriodo'])->name('administrador.panel-control.habilitar-periodo');
    Route::get('/administrador/panel-control/habilitar-periodo', [AdministradorPanelControlController::class, 'indice']);
    Route::post('/administrador/panel-control/actualizar-periodo', [AdministradorPanelControlController::class, 'actualizarPeriodo'])->name('administrador.panel-control.actualizar-periodo');
    Route::get('/administrador/panel-control/actualizar-periodo', [AdministradorPanelControlController::class, 'indice']);
    Route::post('/administrador/panel-control/actualizar-plan-estudio', [AdministradorPanelControlController::class, 'actualizarPlanEstudio'])->name('administrador.panel-control.actualizar-plan-estudio');
    Route::get('/administrador/panel-control/actualizar-plan-estudio', [AdministradorPanelControlController::class, 'indice']);
    Route::post('/administrador/panel-control/eliminar', [AdministradorPanelControlController::class, 'eliminar'])->name('administrador.panel-control.eliminar');
    Route::get('/administrador/panel-control/eliminar', [AdministradorPanelControlController::class, 'indice']);
    Route::post('/administrador/panel-control/crear', [AdministradorPanelControlController::class, 'crear'])->name('administrador.panel-control.crear');
    Route::get('/administrador/panel-control/crear', [AdministradorPanelControlController::class, 'indice']);

    Route::get('/administrador/horarios/', [AdministradorHorarioController::class, 'indice'])->name('administrador.horarios');
});
Route::middleware(['auth', 'administrativo'])->group(function () {
    Route::get('/administrativo/publicaciones/{tipo?}', [PublicacionController::class, 'indice'])->name('administrativo.publicaciones');
    Route::get('/administrativo/publicaciones/publicar', [PublicacionController::class, 'indice']);
    Route::post('/administrativo/publicaciones/publicar', [PublicacionController::class, 'publicar'])->name('administrativo.publicaciones.publicar');
    Route::get('/administrativo/publicaciones/eliminar', [PublicacionController::class, 'indice']);
    Route::post('/administrativo/publicaciones/eliminar', [PublicacionController::class, 'eliminar'])->name('administrativo.publicaciones.eliminar');
    Route::get('/administrativo/publicaciones/actualizar', [PublicacionController::class, 'indice']);
    Route::post('/administrativo/publicaciones/actualizar', [PublicacionController::class, 'actualizar'])->name('administrativo.publicaciones.actualizar');
});
Route::middleware(['auth', 'docente'])->group(function () {
    Route::get('/docente/docencias/indice/{periodo?}/{gestion?}', [DocenteDocenciaController::class, 'indice'])->name('docente.docencias');
    Route::get('/docente/docencias/buscar', [DocenteDocenciaController::class, 'buscar'])->name('docente.docencias.buscar');
    Route::get('/docente/docencias/ponderaciones/indice/{aperturaId}/{periodo?}/{gestion?}', [DocentePonderacionController::class, 'indice'])->name('docente.ponderaciones');
    Route::post('/docente/docencias/ponderaciones/crear', [DocentePonderacionController::class, 'crear'])->name('docente.ponderaciones.crear');
    Route::get('/docente/docencias/ponderaciones/crear', [DocentePonderacionController::class, 'indice']);
    Route::post('/docente/docencias/ponderaciones/eliminar', [DocentePonderacionController::class, 'eliminar'])->name('docente.ponderaciones.eliminar');
    Route::get('/docente/docencias/ponderaciones/eliminar', [DocentePonderacionController::class, 'indice']);
    Route::post('/docente/docencias/ponderaciones/actualizar', [DocentePonderacionController::class, 'actualizar'])->name('docente.ponderaciones.actualizar');
    Route::get('/docente/docencias/ponderaciones/actualizar', [DocentePonderacionController::class, 'indice']);
    Route::post('/docente/docencias/ponderaciones/actualizar-apertura', [DocentePonderacionController::class, 'actualizarApertura'])->name('docente.ponderaciones.actualizar-apertura');
    Route::get('/docente/docencias/ponderaciones/actualizar-apertura', [DocentePonderacionController::class, 'indice']);
    Route::get('/docente/docencias/notas/indice/{aperturaId}/{periodo?}/{gestion?}', [DocenteNotaController::class, 'indice'])->name('docente.notas');
    Route::get('/docente/docencias/notas/exportar-pdf/{aperturaId}/{periodo?}/{gestion?}', [DocenteNotaController::class, 'exportarPdf'])->name('docente.notas.exportar-pdf');
    Route::post('/docente/docencias/notas/registrar', [DocenteNotaController::class, 'registrar'])->name('docente.notas.registrar');
    Route::get('/docente/docencias/notas/registrar', [DocenteNotaController::class, 'indice']);
    Route::get('/docente/docencias/inscritos/indice/{aperturaId}/{periodo?}/{gestion?}', [DocenteInscritoController::class, 'indice'])->name('docente.inscritos');
    Route::get('/docente/docencias/inscritos/exportar-pdf/{aperturaId}/{periodo?}/{gestion?}', [DocenteInscritoController::class, 'exportarPdf'])->name('docente.inscritos.exportar-pdf');
    
    Route::get('/docente/anuncios/{pagina?}', [DocenteAnuncioController::class, 'indice'])->where('pagina', '[1-9]+')->name('docente.anuncios');
    Route::get('/docente/anuncios/publicar', [DocenteAnuncioController::class, 'indice']);
    Route::post('/docente/anuncios/publicar', [DocenteAnuncioController::class, 'publicar'])->name('docente.anuncios.publicar');
    Route::get('/docente/anuncios/eliminar', [DocenteAnuncioController::class, 'indice']);
    Route::post('/docente/anuncios/eliminar', [DocenteAnuncioController::class, 'eliminar'])->name('docente.anuncios.eliminar');
    Route::get('/docente/anuncios/actualizar', [DocenteAnuncioController::class, 'indice']);
    Route::post('/docente/anuncios/actualizar', [DocenteAnuncioController::class, 'actualizar'])->name('docente.anuncios.actualizar');
});
Route::middleware(['auth', 'auxiliar'])->group(function () {
    Route::get('/auxiliar/auxiliaturas/indice/{periodo?}/{gestion?}', [AuxiliarAuxiliaturaController::class, 'indice'])->name('auxiliar.auxiliaturas');
    Route::get('/auxiliar/auxiliaturas/buscar', [AuxiliarAuxiliaturaController::class, 'buscar'])->name('auxiliar.auxiliaturas.buscar');
    Route::get('/auxiliar/auxiliaturas/ponderaciones/indice/{aperturaId}/{periodo?}/{gestion?}', [AuxiliarPonderacionController::class, 'indice'])->name('auxiliar.ponderaciones');
    Route::post('/auxiliar/auxiliaturas/ponderaciones/crear', [AuxiliarPonderacionController::class, 'crear'])->name('auxiliar.ponderaciones.crear');
    Route::get('/auxiliar/auxiliaturas/ponderaciones/crear', [AuxiliarPonderacionController::class, 'indice']);
    Route::post('/auxiliar/auxiliaturas/ponderaciones/eliminar', [AuxiliarPonderacionController::class, 'eliminar'])->name('auxiliar.ponderaciones.eliminar');
    Route::get('/auxiliar/auxiliaturas/ponderaciones/eliminar', [AuxiliarPonderacionController::class, 'indice']);
    Route::post('/auxiliar/auxiliaturas/ponderaciones/actualizar', [AuxiliarPonderacionController::class, 'actualizar'])->name('auxiliar.ponderaciones.actualizar');
    Route::get('/auxiliar/auxiliaturas/ponderaciones/actualizar', [AuxiliarPonderacionController::class, 'indice']);
    Route::post('/auxiliar/auxiliaturas/ponderaciones/actualizar-apertura', [AuxiliarPonderacionController::class, 'actualizarApertura'])->name('auxiliar.ponderaciones.actualizar-apertura');
    Route::get('/auxiliar/auxiliaturas/ponderaciones/actualizar-apertura', [AuxiliarPonderacionController::class, 'indice']);
    Route::get('/auxiliar/auxiliaturas/notas/indice/{aperturaId}/{periodo?}/{gestion?}', [AuxiliarNotaController::class, 'indice'])->name('auxiliar.notas');
    Route::get('/auxiliar/auxiliaturas/notas/exportar-pdf/{aperturaId}/{periodo?}/{gestion?}', [AuxiliarNotaController::class, 'exportarPdf'])->name('auxiliar.notas.exportar-pdf');
    Route::post('/auxiliar/auxiliaturas/notas/registrar', [AuxiliarNotaController::class, 'registrar'])->name('auxiliar.notas.registrar');
    Route::get('/auxiliar/auxiliaturas/notas/registrar', [AuxiliarNotaController::class, 'indice']);
    Route::get('/auxiliar/auxiliaturas/inscritos/indice/{aperturaId}/{periodo?}/{gestion?}', [AuxiliarInscritoController::class, 'indice'])->name('auxiliar.inscritos');
    Route::get('/auxiliar/auxiliaturas/inscritos/exportar-pdf/{aperturaId}/{periodo?}/{gestion?}', [AuxiliarInscritoController::class, 'exportarPdf'])->name('auxiliar.inscritos.exportar-pdf');
    
    Route::get('/auxiliar/anuncios', [AuxiliarAnuncioController::class, 'indice'])->name('auxiliar.anuncios');
    Route::get('/auxiliar/anuncios/publicar', [AuxiliarAnuncioController::class, 'indice']);
    Route::post('/auxiliar/anuncios/publicar', [AuxiliarAnuncioController::class, 'publicar'])->name('auxiliar.anuncios.publicar');
    Route::get('/auxiliar/anuncios/eliminar', [AuxiliarAnuncioController::class, 'indice']);
    Route::post('/auxiliar/anuncios/eliminar', [AuxiliarAnuncioController::class, 'eliminar'])->name('auxiliar.anuncios.eliminar');
    Route::get('/auxiliar/anuncios/actualizar', [AuxiliarAnuncioController::class, 'indice']);
    Route::post('/auxiliar/anuncios/actualizar', [AuxiliarAnuncioController::class, 'actualizar'])->name('auxiliar.anuncios.actualizar');
});
Route::middleware(['auth', 'estudiante'])->group(function () {
    Route::get('/estudiante/inscripciones/indice/{periodo?}/{gestion?}', [InscripcionController::class, 'indice'])->name('estudiante.inscripciones');
    Route::post('/estudiante/inscripciones/indice', [InscripcionController::class, 'registrarInscripcion'])->name('estudiante.inscripciones.registrar-inscripcion');
    Route::get('/estudiante/inscripciones/buscar', [InscripcionController::class, 'buscar'])->name('estudiante.inscripciones.buscar');
    Route::post('/estudiante/inscripciones/eliminar', [InscripcionController::class, 'eliminar'])->name('estudiante.inscripciones.eliminar');
    Route::get('/estudiante/inscripciones/eliminar', [InscripcionController::class, 'indice']);
    Route::post('/estudiante/inscripciones/boleta-pdf', [InscripcionController::class, 'boletaPdf'])->name('estudiante.inscripciones.boleta-pdf');
    Route::get('/estudiante/inscripciones/boleta-pdf', [InscripcionController::class, 'indice']);
    Route::get('/estudiante/notas/indice/{periodo?}/{gestion?}', [NotaController::class, 'indice'])->name('estudiante.notas');
    Route::post('/estudiante/notas/buscar', [NotaController::class, 'buscarNotas'])->name('estudiante.notas.buscar');
    Route::get('/estudiante/notas/detalle/{aperturaId}/{periodo?}/{gestion?}', [NotaController::class, 'detalle'])->name('estudiante.notas.detalle');
    Route::get('/estudiante/horarios/indice/{periodo?}/{gestion?}', [HorarioController::class, 'indice'])->name('estudiante.horarios');
    Route::post('/estudiante/horarios/buscar', [HorarioController::class, 'buscar'])->name('estudiante.horarios.buscar');
    Route::post('/estudiante/horarios/pdf', [HorarioController::class, 'pdf'])->name('estudiante.horarios.pdf');
});